### PR TITLE
fix: 🐛 make pfv mock responsive to bots again

### PR DESCRIPTION
**Pull request by limwa**
This commit removes an if statement that was added in #1.

image

As you can see, those changes were not taken well by the community and I seriously think you should consider reverting them :D

### CODE REVIEW

**Comment by gui1612** [comment]
Indeed, I think this would be a good idea. :rocket:

**Comment by LucasSexo** [comment]
we, as the end users did not like the recent changes to botinha. criei uma conta só para reclamar

**Comment by jfbaltazar** [comment]
Muito Obrigado

por se preocupar comigo
depois que minha família foi
**Assaltada**

**Comment by limwa** [comment]
Ladies and gentlemen, we did it. 38c78a5dc9566b49960e0d4983a0da777af16579 fixed our issue.

**Comment by gui1612** [comment]
:rocket:

**Comment by limwa** [comment]
🚀

**Comment by LucasSexo** [comment]
🚀

**Pull request closed without merging**
